
variables:
  - name: location
    value: "ukwest"

  - name: serviceConnection
    value: "test-hub-sbc"

  - name: subscriptionId
    value: "32eda50c-51c8-4c0f-b533-5cf733e400c0"

  - name: vmImageName
    value: "ubuntu-20.04"

  - name: folderPath
    value: "Landing-Zones/hub-sbc/hub-ukw"

  - name: fileName
    value: "hub-ukw"

  - name: environmentName
    value: "hub-ukw"

  - name: artifactStorageAccountName
    value: "artifactshubukwsa001"

  - name: artifactStorageAccountRG
    value: "artifact-hub-ukw-rg-001"

  - name: artifactStorageAccountContainer
    value: "artifactshubukwcontainer001"   

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - components/biceps/resourcegroup
    - components/biceps/routetable
    - components/biceps/virtualnetwork

resources:
  repositories:
    - repository: bicep-pipeline-templates
      type: git
      name: bicep-pipeline-templates
      #ref: ${{ variables.pipelineVersion }}

stages:

  - template: /pipeline-templates/main.yml@bicep-pipeline-templates
    parameters:
      serviceConnection: ${{ variables.serviceConnection }}
      location: ${{ variables.location }}
      subscriptionId: ${{ variables.subscriptionId }}
      folderPath: ${{ variables.folderPath }}
      environmentName: ${{ variables.environmentName }}
      fileName: ${{ variables.fileName }}
      vmImageName: ${{ variables.vmImageName }}
      artifactStorageAccountName: ${{ variables.artifactStorageAccountName }}
      artifactStorageAccountRG: ${{ variables.artifactStorageAccountRG }}
      artifactStorageAccountContainer: ${{ variables.artifactStorageAccountContainer}}
      
 