name: CI/CD Pipeline

# Triggers the workflow when pushing to the main branch with specific path filters
on:
  push:
    branches:
      - main
    paths:
      - 'components/biceps/resourcegroup/**'
      - 'components/biceps/routetable/**'
      - 'components/biceps/virtualnetwork/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Define variables equivalent to Azure Pipeline variables
    env:
      location: "uksouth"
      vmImageName: "ubuntu-20.04"
      folderPath: "Landing-Zones/hub-sbc"
      environmentName: "hub-uks"
      artifactStorageAccountName: "artifactshubukssa001"
      artifactStorageAccountRG: "artifact-hub-uks-rg-001"
      artifactStorageAccountContainer: "artifactshubukscontainer001"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # You need to call an external pipeline template (like in Azure Pipelines), here it can be another workflow call if available in the same repo or another repo.
      # Since GitHub Actions does not have the same templating mechanism, we assume you reference a reusable workflow.

      - name: Trigger reusable workflow (bicep-pipeline-templates)
        uses: SreeShaji67/bicep-pipeline-templates/pipeline-templates/main.yml@main # Reference reusable workflow in another repo
        with:
          location: ${{ env.location }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          folderPath: "${{ env.folderPath }}/${{ env.environmentName }}"
          environmentName: ${{ env.environmentName }}
          fileName: "${{ env.environmentName }}.bicep"
          vmImageName: ${{ env.vmImageName }}
          artifactStorageAccountName: ${{ env.artifactStorageAccountName }}
          artifactStorageAccountRG: ${{ env.artifactStorageAccountRG }}
          artifactStorageAccountContainer: ${{ env.artifactStorageAccountContainer }}

